#!/bin/bash

# Copy the tutorial notebook to the working directory that is presented upon launch via MyBinder
cp -r /usr/src/app/tutorial.ipynb ~/.


# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"