#!/bin/bash

# Copy the contents of the repo to the working directory that is presented upon launch via MyBinder
cp -r /usr/src/app/* ~/


# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"